### Get all accessories
http://localhost:3000/accessories

### Get a specific accessory
http://localhost:3000/accessories/0dc78ef1-38ab-461a-83cb-569424f7c337

### Add new accessories
POST http://localhost:3000/accessories
Content-Type: application/json

[
  {
    "name": "Aretes de Plata",
    "description": "Aretes de plata con diseño elegante, perfectos para cualquier ocasión.",
    "img": "/images/accessories/aretes-plata.jpg",
    "category": "Complementos",
    "handmade": true,
    "available": true,
    "highlighted": true,
    "price": 12.99,
    "stock": 25
  }
]

### Update an existing accessory
PUT http://localhost:3000/accessories/4aab64f6-73bd-4f68-8be6-b501a71ec995
Content-Type: application/json

  {
    "name": "Correa de cuerooooo",
    "description": "Correa ajustable de cuero genuino, resistente y con hebilla metálica.",
    "img": "/images/accessories/correa-cuero.jpg",
    "category": "Ropa",
    "handmade": false,
    "available": true,
    "highlighted": false,
    "price": 29.99,
    "stock": 15
  }


### Partially update an existing accessory
PATCH http://localhost:3000/accessories/af711ca8-895e-43b5-bd8d-9d266a45dcb7
Content-Type: application/json

  {
    "price": 500.001
  }

### Delete an existing accessory
DELETE http://localhost:3000/accessories/777d84be-1929-4615-b221-e154491799e4