### Get all accessories
http://localhost:3000/accessories

### Get a specific accessory
http://localhost:3000/accessories/67d91ccc-5943-11f1-accf-f0736fd2cf99

### Add new accessories
POST http://localhost:3000/accessories
Content-Type: application/json

[
  {
    "name": "Aretes de Plata",
    "description": "Aretes de plata con diseño elegante, perfectos para cualquier ocasión.",
    "img": "https://co.anabuendiaofficial.com/cdn/shop/products/EarringCoprisilver-arete-plata-filigrana-2.jpg?v=1612899945&width=600",
    "category_id": 3,
    "handmade": false,
    "available": true,
    "highlighted": true,
    "price": 12.99,
    "stock": 25,
    "rating": 4
  }
]

### Update an existing accessory
PUT http://localhost:3000/accessories/67d91ccc-5943-11f1-accf-f0736fd2cf99
Content-Type: application/json

  {
    "category_id": 2,
    "name": "LLavero",
    "description": "Llavero artesanal",
    "img": "https://i.pinimg.com/736x/45/1a/26/451a263ff27dc23863d8456f53593ae3.jpg",
    "handmade": true,
    "available": true,
    "highlighted": true,
    "price": 25000.00,
    "stock": 30,
    "rating": 5
  }


### Partially update an existing accessory
PATCH http://localhost:3000/accessories/67d91ccc-5943-11f1-accf-f0736fd2cf90
Content-Type: application/json

  {
    "price": 500.05
  }

### Delete an existing accessory
DELETE http://localhost:3000/accessories/57f24da8-595a-11f1-8925-c6266cac1a7d



### get all accessory categories
http://localhost:3000/accessory-categories

### update an existing accessory category
PUT http://localhost:3000/accessory-categories/8
Content-Type: application/json

  {
    "name": "Pulseras"
  }

### create a new accessory category
POST http://localhost:3000/accessory-categories
Content-Type: application/json

  {
    "name": "Collares"
  }

### delete an existing accessory category
DELETE http://localhost:3000/accessory-categories/3


### get all accessory materials
http://localhost:3000/accessory-materials


### create a new accessory material
POST http://localhost:3000/accessory-materials
Content-Type: application/json

  {
    "name": "Murano"
  }

### update an existing accessory material
PUT http://localhost:3000/accessory-materials/8
Content-Type: application/json

  {
    "name": "Cuero"
  }

### delete an existing accessory material
DELETE http://localhost:3000/accessory-materials/5